#!/bin/bash

printf "Copying files from distribution directories to target directories.\n"
cp ./scripts/* /usr/local/bin
mkdir -p /root/chef-repo/cookbooks/debian_prep/spec/unit
mkdir -p /root/chef-repo/cookbooks/debian_prep/recipes
cp ./debian_prep/Gemfile /root/chef-repo/cookbooks/debian_prep/spec
cp ./debian_prep/Rakefile /root/chef-repo/cookbooks/debian_prep/spec
cp -r ./debian_prep/recipes/* /root/chef-repo/cookbooks/debian_prep/recipes
cp ./debian_prep/spec/spec_helper.rb /root/chef-repo/cookbooks/debian_prep/spec/.
cp -r ./debian_prep/spec/unit/recipes/* /root/chef-repo/cookbooks/debian_prep/spec/unit/recipes

printf "Executing Chef to complete provisioning the instance.\n"
cd /root/chef-repo/cookbooks
chef-client --local-mode --override-runlist debian_prep

